### ISSUE TITLE
/lti can return blank page 

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5290] opened 2024-01-14 21:08 UTC
When I landed on the https://dodona.be/lti/content_selection page, I got a blank page. The same happens with /lti/series_and_activities. For other /lti links, there is some explanation, but those 2 pages are completely blank. I would argue that they need the same page as other f.e. non-existing pages, or requests that return "500: internal server error".

This image of /lti/series_and_activities apparently returns a 401: unauthorized. Normally you get redirected to your home-page then.
![image](https://github.com/dodona-edu/dodona/assets/93756910/e0e643c9-9e5a-49a2-b1e5-2cf8182e783d)

**Comment by BWindey** [comment] 2024-01-14 21:09
Would probably better server under the "enhancement" tag, but that's not available when picking a template.

**Comment by BWindey** [comment] 2024-01-14 22:30
The same happens with:
- /submissions/{submission_id}/annotations (406: unacceptable, empty screen)
- /users/{own_user_id}/api_tokens (406: Not Acceptable, enkel als JSON te zien)

**Comment by jorg-vr** [comment] 2024-01-15 08:41
Thanks for notifying us on this issue.

Although in a perfect world every non available page returns the correct 4xx error code, with a relevant redirect, this is a non issue.

These pages are only meant to be used in the LTI flow, which is meant for integration in ufora and ILearn. They should not be usable in any other context and they aren't, so that is working as intended.

I wouldn't spend time on updating this behavior as any changes here should also be tested with ILearn and Ufora, which is a hassle. 

I would suggest closing this issue as wontfix: @bmesuere do you agree?

**Closed** 2024-01-15 09:28 UTC
Labels: feature
