### ISSUE TITLE
Make title field broader when saving annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5153] opened 2023-11-14 17:12 UTC
Is there something to object against making the title field as wide as the content field when saving annotations. Right now, the title field is quite narrow. Giving both the same width would improve the UX.

![image](https://github.com/dodona-edu/dodona/assets/5736113/d4469c30-6b41-4ce9-be01-65e6de4aa252)

**Comment by bmesuere** [comment] 2023-11-14 18:28
The actual UI issue is that the input:text is on a newline and not between the checkbox and buttons.

**Comment by jorg-vr** [comment] 2023-11-16 12:28
I cannot reproduce this on any page width on my machine in either chrome or firefox.
Can anyone else reproduce this easily? Otherwise I would close this as a very specific layout issue that does not impact many users

**Closed** 2023-11-16 14:07 UTC
Labels: bug
