### ISSUE TITLE
Two rightmost menus in navigation bar cannot be expanded

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2999] opened 2021-08-21 13:14 UTC
Playing around with latest chart deploy on naos, I was unable to use the two rightmost menus in the navigation bar. Just to check if no bug was introduced with these menus.

**Comment by chvp** [comment] 2021-08-21 13:16
I can't reproduce this (on Naos).

**Comment by pdawyndt** [comment] 2021-08-21 14:13
Checked it again. Doesn't happen on the homepage, but e.g. when on a course page (https://naos.ugent.be/nl/courses/1/). Actually, series menus don't work there neither.

**Comment by chvp** [comment] 2021-08-21 16:49
This seems to be an issue with #2598's branch. I can't reproduce this on latest develop locally, while I can reproduce this on that branch (both locally and on naos). (I did indeed only test on the homepage, I was able to reproduce this on a course page.) Closing this since this issue does not exist on one of our main branches.

**Closed by chvp** 2021-08-21 16:49 UTC
Labels: bug
