### ISSUE TITLE
Info balloon "missed deadline but your last submission is correct" pops up before deadline is expired

### ISSUE THREAD

**Issue by gubogaer** [dodona-edu/dodona#2312] opened 2020-10-03 13:17 UTC
In the r course "Statistiek: introductie tot R" we have noticed 2 student submissions that were correct but marked with a red cross in the home page and an info balloon saying that the they missed the deadline and their last solution was correct. The deadline of this series expires on "07 oktober 2020 23:00". A reassessment of these exercises solved the problem for now.

**Comment by pdawyndt** [comment] 2020-10-03 13:31
Also related to #2079?

**Comment by gubogaer** [comment] 2020-10-03 13:49
The issue now occurred 3 times on the same exercise, in the git commits I've noticed that both the description and the evaluation file have had an update in the passed 24 hours but I don't see this exercise being deleted or added. I haven't noticed a deadline change but I will ask around if maybe someone else did.

image for clarification:
![image](https://user-images.githubusercontent.com/56388795/94992888-6b150780-058d-11eb-83b5-b670189b4866.png)

**Comment by gubogaer** [comment] 2020-10-03 14:25
The deadline has been changed from 05 oktober 2020 23:00 to 07 oktober 2020 23:00. So even if this deadline wasn't updated it shouldn't be a problem yet.

**Comment by chvp** [comment] 2021-04-14 09:48
I am unable to reproduce this issue. A number of caching fixes have been committed since this was reported. Feel free to reopen or add a comment if you notice this happening again.

**Closed by chvp** 2021-04-14 09:48 UTC
Labels: bug, high priority
