### ISSUE TITLE
Students appear to have no access to public files

### ISSUE THREAD

**Issue by pverscha** [dodona-edu/dodona#1614] opened 2019-12-25 10:55 UTC
Some students contacted me earlier this week (for the "Computergebruik" course) and informed that they no longer have access to the files linked to an exercise. I've tried this myself (as did @pdawyndt) and we both have access, even in a clean browser (so no cache-related issues arise).

This is a screenshot that I received:
![image](https://user-images.githubusercontent.com/9608686/71443791-44c46080-270d-11ea-8d85-880e647c64d7.png)

A few example exercises for which this issue arises:
https://dodona.ugent.be/nl/courses/186/series/1974/exercises/614577564/
https://dodona.ugent.be/nl/courses/186/series/1841/exercises/208928702/
https://dodona.ugent.be/nl/courses/186/series/1841/exercises/1916276684/

**Comment by charvp** [comment] 2019-12-25 17:24
Duplicate of #1588. (All the exercises that you linked were private exercises.)

**Closed by charvp** 2019-12-25 17:24 UTC

**Comment by pdawyndt** [comment] 2019-12-25 18:19
This seems to have been resolved by making the exercises public. However, I believe that our policy was that a private exercises that is included in a course, should behave as a public exercise (e.g. linked files should be accessible). Do we abandon this policy?

**Comment by charvp** [comment] 2019-12-25 20:49
This policy has not changed. Making the exercises public is a workaround until #1588 is fixed. Hence why this bug was marked as a duplicate, not as a wontfix or an invalid bug.
