### ISSUE TITLE
multilingual courses

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1260] opened 2019-09-07 09:50 UTC
Offering the same course in Dutch and English requires two separate courses on Dodona. However, all it would take to make a single multilingual course is:

- multilingual course properties (name, description)
- multilingual series propertie (name, description)

This would prevent having to maintain two separate courses, students being confused about what course they would need to subscribe to, separate configurations and redirection paths of Indianio during evaluations and exams, and would merge all user statistics in a more natural way.

**Comment by charvp** [comment] 2019-09-07 09:51
Duplicate of #236

**Closed by charvp** 2019-09-07 09:51 UTC

**Comment by pdawyndt** [comment] 2019-09-07 09:54
Shows it's a yearly recurring theme. Original issue apparently has been rescheduled from release 2.5 to `untriaged`. Maybe we should reconsider putting it back on the roadmap for one of the coming releases.
