### ISSUE TITLE
Heatmap Issue - Missing Data November / December

### ISSUE THREAD

**Issue by RobbeW** [dodona-edu/dodona#4264] opened 2022-12-21 08:32 UTC
Hi

I have noticed a bug in my teacher overview in Dodona. The heatmap is missing the activity logs for the months November and December, while the students have submitted code exercises. 

Additional information: 
- They use the Single Sign-On authentication using Microsoft365; 
- Browser used: Google Chrome 

Screengrab: 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/59528716/208856648-6abc7d3c-c96f-48fd-9647-a444b7789dd4.png">

**Comment by chvp** [comment] 2022-12-21 08:33
I think this is actually the same issue as #4263, in that we (can) show outdated info when the page is loaded and recalculate the info in the background.

**Comment by chvp** [comment] 2022-12-21 08:34
Can you check if refreshing the page shows updated data?

**Comment by RobbeW** [comment] 2022-12-21 08:36
Hard refresh seemed to do the trick when checking an individual student! On first load, it shows outdated info. Problem with some in-browser cache?

**Comment by chvp** [comment] 2022-12-21 09:54
It being caused by the server-level cache seems more likely to me. I'm going to close this issue in favor of #4263, since they both have the same root cause (mostly it not being clear that outdated info might be shown, and the outdated info being shown until page reload).

**Closed by chvp** 2022-12-21 09:54 UTC
Labels: bug, duplicate
