### ISSUE TITLE
Deploying develop on naos fails

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/dodona#3645] opened 2022-05-22 09:26 UTC
Currently, Dodona seems to make use of 2 versions of the same gem 'strscan': 3.0.1 and 3.0.3. This causes issues when deploying to Naos, as it will show an error on any page related to naos.ugent.be.
Steps to reproduce:
run "Deploy to Naos" on the "develop" branch.
Output on naos.ugent.be:
![naos-error](https://user-images.githubusercontent.com/53743234/169688582-219c69a7-c918-4030-a6c3-85a6f03a766c.PNG)

Error details:
```
You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.3. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:309:in `check_for_activated_spec!'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:25:in `block in setup'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:24:in `map'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:24:in `setup'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler.rb:150:in `setup'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
  /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
  <internal:/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  <internal:/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `activate_gem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:544:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

Process output:
```
Error: The application encountered the following error: You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.3. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem. (Gem::LoadError)
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:309:in `check_for_activated_spec!'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:25:in `block in setup'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/spec_set.rb:136:in `each'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:24:in `map'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/runtime.rb:24:in `setup'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler.rb:150:in `setup'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
    /usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
    <internal:/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    <internal:/usr/share/rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `activate_gem'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:221:in `block in run_load_path_setup_code'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:544:in `running_bundler'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:220:in `run_load_path_setup_code'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:91:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by bmesuere** [comment] 2022-05-22 09:28
There was already an issue for this: #3574
I'll close this one and bump the priority of the existing one.

**Comment by bmesuere** [comment] 2022-05-22 10:49
I'll reopen this, because there's a problem deploying develop as well. strscan was bumped to 3.0.3 by the rails update two weeks ago. Since it doesn't require an explicit version, we can probably just undo that change.

**Comment by chvp** [comment] 2022-05-22 11:47
Actual problem and workaround is described here: https://bytemeta.vip/repo/phusion/passenger/issues/2409

**Comment by chvp** [comment] 2022-05-22 11:55
Work-around PR here: https://github.com/dodona-edu/dodona-ansible/pull/144
I've deployed this to mestra and naos and confirmed that it works there (which means we can probably close this issue).

**Closed** 2022-07-04 07:47 UTC
Labels: bug, high priority
