### ISSUE TITLE
Copy series

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3329] opened 2022-01-25 15:43 UTC
Would be nice if series could be copied (use case: create test/exam series with alternative deadlines). At least with the same course, but also between courses.

Issue jointly created with @toonijn

**Comment by BTWS2** [comment] 2022-01-25 15:52
I asked this in the past (#2809), so +1 for this issue.

**Comment by niknetniko** [comment] 2022-01-25 16:04
Duplicate of #2809, as mentioned. Closing this issue, since it is the newer one.

**Closed by niknetniko** 2022-01-25 16:04 UTC
Labels: feature
