### ISSUE TITLE
Inconsistent reponse of series analytics if not enough data is available

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3393] opened 2022-02-14 19:30 UTC
Submissions over time keeps "loading" if not a single submission was made:

![image](https://user-images.githubusercontent.com/5736113/153932858-7a1db989-43d9-487c-9026-b88105c9ff84.png)

All three other series analytics show a message (after loading has finished) that there's not enough data to create a graph:

![image](https://user-images.githubusercontent.com/5736113/153932908-80f11110-f393-41d8-888f-17f113226c36.png)

**Comment by chvp** [comment] 2022-02-14 19:31
Duplicate of #3367 (although it is good to know that it's because of empty data).

**Closed by chvp** 2022-02-14 19:31 UTC
Labels: bug
