### ISSUE TITLE
`js.options` label in search checkboxes

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#4301] opened 2023-01-06 09:20 UTC
1. Go to 
https://dodona.ugent.be/en/courses/
or 
https://dodona.ugent.be/en/questions/
or 
https://dodona.ugent.be/en/series/???/scoresheet/

2. Click the three vertical dots.

Proposed solution: Change the label or remove `js.options` dropdown header.
![image](https://user-images.githubusercontent.com/56451049/210969039-142aae31-fa8c-496d-b97b-5de0ff7e1100.png)
![image](https://user-images.githubusercontent.com/56451049/210969350-675c91ec-e142-4848-8f84-7ed8ca5e126a.png)
![image](https://user-images.githubusercontent.com/56451049/210969812-ee189be5-f80c-4578-ba93-5c8df72e4d22.png)

**Comment by chvp** [comment] 2023-01-06 09:26
Duplicate of #4094.

**Closed by chvp** 2023-01-06 09:26 UTC
Labels: bug
