### ISSUE TITLE
Widen scope of reusing annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5253] opened 2023-12-22 08:56 UTC
I'm answering questions from students about exercises that I have assessed during last year's exam and I'm getting questions that I could answer with annotations that I have saved for this exercise, but in last year's course. So I could efficiently reuse annotations for the same exercise, although they have been added in other courses.

I also want to reuse previous saved annotations from other exercises, as they are general enough to be reused across exercises.

I also want to reuse previous annotations, even though I haven't saved them (because I forgot or didn't conceive them as reusable at the time they were added).

**Suggestion**: In analogy with scoping courses and activities in separate tabs when searching for them, we could also scope annotations when searching for them. This would make annotations far more reusable, across the exercise/course/user boundaries they are locked in right now. Again, this would be another incentive to invest in formulating these annotations.

**Comment by jorg-vr** [comment] 2023-12-22 08:59
this is a duplicate of #4993

**Closed by jorg-vr** 2023-12-22 08:59 UTC
Labels: feature
